language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  firefox: latest-esr
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=5.1
matrix:
  fast_finish: true
before_install:
- npm install csslint jshint
- which csslint
- which jshint
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
- bin/pylint --py3k --disable=no-absolute-import src/collective/glossary
after_success:
- pip install coverage
- coverage run bin/test --layer=\!Robot
# Coveralls
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
