language: python
python: 2.7
sudo: false
cache:
  directories:
  - $HOME/.pylint.d
  - eggs
  - parts/node
addons:
  firefox: 45.8.0esr
env:
- PLONE_VERSION=5.1
matrix:
  fast_finish: true
before_install:
# FIXME: I have no idea how and why six==1.11.0 is being installed
- pip uninstall -y six
install:
- sed -ie "s#test-5.1#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
- bin/pylint --py3k --disable=no-absolute-import src/collective/glossary
after_success:
- pip install coverage
- coverage run bin/test --layer=\!Robot
# Coveralls
- pip install coveralls
- coveralls
# Codacy
- coverage xml
- pip install codacy-coverage
- python-codacy-coverage -r coverage.xml
notifications:
  irc: irc.freenode.org#plone-testing
