name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        plone-version: ["5.2", "6.0"]

    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Install system libraries
        run: sudo apt-get install libxml2-dev libxslt1-dev libjpeg-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          pip install -U selenium
      - name: Test with tox
        run: tox
        env:
          PLONE: ${{ matrix.plone-version }}
